---
- name: Ensure shopt options are applied to the .bashrc file
  ansible.builtin.lineinfile:
    dest: "{{ __bashrc_file }}"
    regexp: ^{{ item }}$
    line: "{{ item }}"
  with_items: "{{ admin_user__bash_shopt_options }}"

- name: Ensure bash aliases are applied to the .bashrc file
  ansible.builtin.lineinfile:
    dest: "{{ __bashrc_file }}"
    regexp: "{{ item }}"
    line: "{{ item }}"
  with_items: "{{ admin_user__bash_aliases }}"

- name: Ensure additional parameters are applied to the .bashrc file
  ansible.builtin.lineinfile:
    dest: "{{ __bashrc_file }}"
    regexp: ^{{ item.parameter }}=
    line: "{{ item.parameter }}={{ item.value }}"
  with_items:
    - { parameter: HISTSIZE, value: "{{ admin_user__bash_histsize }}" }
    - { parameter: HISTIGNORE, value: "'{{ admin_user__bash_histignore }}'" }
    - { parameter: HISTFILESIZE, value: "{{ admin_user__bash_histfilesize }}" }
    - { parameter: HISTCONTROL, value: "'{{ admin_user__bash_histcontrol }}'" }
    - { parameter: HISTTIMEFORMAT, value: "'{{ admin_user__bash_histtimeformat }}'" }
    - { parameter: PROMPT_COMMAND, value: "'{{ admin_user__bash_prompt_command }}'" }

- name: Ensure vimrc options are applied to the .vimrc file
  ansible.builtin.lineinfile:
    dest: "{{ __vimrc_file }}"
    regexp: ^{{ item }}$
    line: "{{ item }}"
    create: true
    owner: "{{ __vimrc_file_owner }}"
    group: "{{ __vimrc_file_group }}"
    mode: "644"
  with_items: "{{ admin_user__vimrc_options }}"
